library(ggplot2)
library(ggradar)
data = read.table("out/optstatsradar.r", sep="\t", header=TRUE)
cairo_pdf("out/optstatsradar.pdf")
lapply(1:(nrow(data)/3), function(i) { ggradar(data[(3*i-2):(3*i), 1:4], grid.max=250, grid.mid=250, plot.title=data[3*i,1]) })
dev.off()
